---
name: Update Homebrew Formula
on:
  release:
    types: [published]
jobs:
  homebrew-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Homebrew Formula
        uses: garden-io/update-homebrew-action@v1
        if: "!github.event.release.prerelease"
        with:
          packageName: 'aws-jumpcloud'
          templatePath: 'HomebrewFormula/aws-jumpcloud.rb'
          tapRepo: 'CirrusMD/homebrew-aws-jumpcloud'
          srcRepo: 'CirrusMD/aws-jumpcloud'
          authToken: ${{ secrets.GITHUB_TOKEN }}
